# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/107/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/107/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/connor/CLionProjects/Network

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/connor/CLionProjects/Network/cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/107/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/107/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/connor/CLionProjects/Network/cmake-build-debug/CMakeFiles /home/connor/CLionProjects/Network/cmake-build-debug/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/connor/CLionProjects/Network/cmake-build-debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Network

# Build rule for target.
Network: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Network
.PHONY : Network

# fast build rule for target.
Network/fast:
	$(MAKE) -f CMakeFiles/Network.dir/build.make CMakeFiles/Network.dir/build
.PHONY : Network/fast

cache_client.o: cache_client.cc.o

.PHONY : cache_client.o

# target to build an object file
cache_client.cc.o:
	$(MAKE) -f CMakeFiles/Network.dir/build.make CMakeFiles/Network.dir/cache_client.cc.o
.PHONY : cache_client.cc.o

cache_client.i: cache_client.cc.i

.PHONY : cache_client.i

# target to preprocess a source file
cache_client.cc.i:
	$(MAKE) -f CMakeFiles/Network.dir/build.make CMakeFiles/Network.dir/cache_client.cc.i
.PHONY : cache_client.cc.i

cache_client.s: cache_client.cc.s

.PHONY : cache_client.s

# target to generate assembly for a file
cache_client.cc.s:
	$(MAKE) -f CMakeFiles/Network.dir/build.make CMakeFiles/Network.dir/cache_client.cc.s
.PHONY : cache_client.cc.s

cache_lib.o: cache_lib.cc.o

.PHONY : cache_lib.o

# target to build an object file
cache_lib.cc.o:
	$(MAKE) -f CMakeFiles/Network.dir/build.make CMakeFiles/Network.dir/cache_lib.cc.o
.PHONY : cache_lib.cc.o

cache_lib.i: cache_lib.cc.i

.PHONY : cache_lib.i

# target to preprocess a source file
cache_lib.cc.i:
	$(MAKE) -f CMakeFiles/Network.dir/build.make CMakeFiles/Network.dir/cache_lib.cc.i
.PHONY : cache_lib.cc.i

cache_lib.s: cache_lib.cc.s

.PHONY : cache_lib.s

# target to generate assembly for a file
cache_lib.cc.s:
	$(MAKE) -f CMakeFiles/Network.dir/build.make CMakeFiles/Network.dir/cache_lib.cc.s
.PHONY : cache_lib.cc.s

cache_server.o: cache_server.cc.o

.PHONY : cache_server.o

# target to build an object file
cache_server.cc.o:
	$(MAKE) -f CMakeFiles/Network.dir/build.make CMakeFiles/Network.dir/cache_server.cc.o
.PHONY : cache_server.cc.o

cache_server.i: cache_server.cc.i

.PHONY : cache_server.i

# target to preprocess a source file
cache_server.cc.i:
	$(MAKE) -f CMakeFiles/Network.dir/build.make CMakeFiles/Network.dir/cache_server.cc.i
.PHONY : cache_server.cc.i

cache_server.s: cache_server.cc.s

.PHONY : cache_server.s

# target to generate assembly for a file
cache_server.cc.s:
	$(MAKE) -f CMakeFiles/Network.dir/build.make CMakeFiles/Network.dir/cache_server.cc.s
.PHONY : cache_server.cc.s

fifo_evictor.o: fifo_evictor.cc.o

.PHONY : fifo_evictor.o

# target to build an object file
fifo_evictor.cc.o:
	$(MAKE) -f CMakeFiles/Network.dir/build.make CMakeFiles/Network.dir/fifo_evictor.cc.o
.PHONY : fifo_evictor.cc.o

fifo_evictor.i: fifo_evictor.cc.i

.PHONY : fifo_evictor.i

# target to preprocess a source file
fifo_evictor.cc.i:
	$(MAKE) -f CMakeFiles/Network.dir/build.make CMakeFiles/Network.dir/fifo_evictor.cc.i
.PHONY : fifo_evictor.cc.i

fifo_evictor.s: fifo_evictor.cc.s

.PHONY : fifo_evictor.s

# target to generate assembly for a file
fifo_evictor.cc.s:
	$(MAKE) -f CMakeFiles/Network.dir/build.make CMakeFiles/Network.dir/fifo_evictor.cc.s
.PHONY : fifo_evictor.cc.s

lru_evictor.o: lru_evictor.cc.o

.PHONY : lru_evictor.o

# target to build an object file
lru_evictor.cc.o:
	$(MAKE) -f CMakeFiles/Network.dir/build.make CMakeFiles/Network.dir/lru_evictor.cc.o
.PHONY : lru_evictor.cc.o

lru_evictor.i: lru_evictor.cc.i

.PHONY : lru_evictor.i

# target to preprocess a source file
lru_evictor.cc.i:
	$(MAKE) -f CMakeFiles/Network.dir/build.make CMakeFiles/Network.dir/lru_evictor.cc.i
.PHONY : lru_evictor.cc.i

lru_evictor.s: lru_evictor.cc.s

.PHONY : lru_evictor.s

# target to generate assembly for a file
lru_evictor.cc.s:
	$(MAKE) -f CMakeFiles/Network.dir/build.make CMakeFiles/Network.dir/lru_evictor.cc.s
.PHONY : lru_evictor.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Network"
	@echo "... edit_cache"
	@echo "... cache_client.o"
	@echo "... cache_client.i"
	@echo "... cache_client.s"
	@echo "... cache_lib.o"
	@echo "... cache_lib.i"
	@echo "... cache_lib.s"
	@echo "... cache_server.o"
	@echo "... cache_server.i"
	@echo "... cache_server.s"
	@echo "... fifo_evictor.o"
	@echo "... fifo_evictor.i"
	@echo "... fifo_evictor.s"
	@echo "... lru_evictor.o"
	@echo "... lru_evictor.i"
	@echo "... lru_evictor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

